#!/bin/bash 10-no_more_js 11-directories 12-newest_files 13-unique 14-findthatword 15-countthatword 16-whatsnext 17-hidethisword 18-letteronly 19-AZ 20-hiago 21-reverse 22-users_and_homes
tail -n 1 iacta >> iacta
